CREATE TABLE Users (
    id INT IDENTITY(1,1) PRIMARY KEY,

    username NVARCHAR(100) NOT NULL UNIQUE,

    password NVARCHAR(255) NOT NULL,

    role NVARCHAR(50) NOT NULL DEFAULT 'user',

    created_at DATETIME2 DEFAULT SYSDATETIME()
);
GO